### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by cowboysdude** [wearefractal/status#2]

**Comment by yocontra** [comment]
Well, it was a really cool thing and I made a bunch of plugins for it. It should still work if the coffee-script stuff is fixed - or converted from coffee to es6. I made it to use with conky, its a way to access all sorts of things on your computer using the command line.

**Comment by cowboysdude** [comment]
Sorry for leaving no description but Thank you for answering!!! Sometimes things just don't work on windows machines.   Was trying to run it on Node js.... in a function but wasn't quite sure if I was doing it right...It kept throwing errors...

getCPU: function() {
status cpu temp:usage:speed
},

Throws the error right at 'cpu'....... so as a function I couldn't get it to work :(
